
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/logdb # hazir default db ismi - username-password gerekmez
      # !!! MongoDB adresini veriyorum, default db verdigim icin username ve pass yazmaya gerek yok