
server:
  port: 8085

spring:
  application:
    name: gateway

  config:
    import: optional:configserver:http://localhost:8090
    #   optional: ile configserver seklinde isimlendirme yapiyoruz
    #   config server a baglanip kendi konsigurasyonunu buradan almasini sagliyorum