
server:
  port: 8097 # bu applicationin port numarasini yazdik

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # kendisi eureka oldugu icin bir yere kaydolmayacak o yuzden 2 yere false yazildi - server oldugu icin false, client olsa true olurdu
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/